language: node_js
node_js:
- '10'
addons:
  sonarqube:
    organization: "omar97perez-github"
    token:
        secure: c814649ab24e4d4d03d48ef4209c6529372fa748
sudo: false
script:
- cd client
- npm install
# - npm e2e
# - npm test
- sonar-scanner
cache:
  directories:
  - node_modules
