language: node_js
node_js:
- '10'
addons:
  sonarqube:
    organization: "omar97perez-github"
    token:
        secure: 506a037d978b7a018a9f4d719bda2a9bc083c7da
sudo: false
script:
- cd client
- npm install
# - npm e2e
# - npm test
- sonar-scanner
cache:
  directories:
  - node_modules
