language: node_js
node_js:
- '10'
addons:
  sonarqube:
    organization: "omar97perez-github"
    token:
        secure: 31fdac66d1953eb7683fc66b93f64f2b6f2ad586
sudo: false
script:
- cd app
- npm install
# - npm e2e
# - npm test
- sonar-scanner
cache:
  directories:
  - node_modules
